### PR TITLE
9.0.0

### PR DESCRIPTION
**Pull request by jonathantneal**

### CODE REVIEW

**Comment by clarfonthey** [comment]
Why does the project even define a version of `sanitize.css` in the first place? Sure, the tests can require one, but I don't see why this project cares whether you're on version 10 or 11.

**Comment by jonathantneal** [comment]
I understand that, and it bothers me to bump this as a major, which is why I stalled. Unfortunately, I’m not sure how to tell this program that it can use whatever version of sanitize.css you are using locally even if the default version is old. Do you have a better idea, @clarfon?

**Comment by clarfonthey** [comment]
To me it seems like a peer dependency is what's needed.

**Comment by thasmo** [comment]
@jonathantneal, as @clarfon mentioned, maybe defining as a peer dependency does make sense. And you can still define it as dev dependency if needed for tests or similar.

**Pull request merged**
